version: '3.7'
services:
  vault:
    build: .
    hostname: "vault"
    restart: on-failure
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_LOG_LEVEL=debug
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SECURITY_TOKEN
      - AWS_SESSION_TOKEN
    volumes:
      - ./backup:/vault
    cap_add:
      - IPC_LOCK
  consul:
    environment:
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true, \"disable_update_check\": true}"
    image: docker.io/library/consul:1.8.0-rc1
    command: agent -client=0.0.0.0 -server -bootstrap-expect 1 -ui
    volumes:
      - "./etc/data/consul:/consul/data"
