version: '3.7'
services:
  vault:
    build: .
    hostname: "vault"
    restart: on-failure
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_LOG_LEVEL=debug
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SECURITY_TOKEN
      - AWS_SESSION_TOKEN
    ports:
      - 8200:8200
    volumes:
      - ./backup:/vault
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.whoa.bot`)"
