version: '2'
services:
  vault-ddb:
    image: "vault:1.4.1"
    hostname: "vault"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - 8200:8200
    volumes:
      - ./config:/config
      - ./.aws:/root/.aws
    entrypoint: vault server -config=/config/vault-ddb.hcl
  vault-s3:
    image: "vault:1.4.1"
    hostname: "vault"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - 8201:8200
    volumes:
      - ./config:/config
      - ./.aws:/root/.aws
    entrypoint: vault server -config=/config/vault-s3.hcl
