version: '3.7'
services:
  vault:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.entrypoints=https"
      - "traefik.http.routers.vault.rule=HostRegexp(`vault.{domain:.+}`)"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
  consul:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault-consul.entrypoints=https"
      - "traefik.http.routers.vault-consul.rule=HostRegexp(`vault-consul.{domain:.+}`)"
      - "traefik.http.services.vault-consul.loadbalancer.server.port=8500"

networks:
  default:
    external:
      name: kitt
