version: '3.7'
services:
  vault:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.${KITT_DOMAIN}`)"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
  consul:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consul.rule=Host(`consul.{KITT_DOMAIN}`)"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"

networks:
  default:
    external:
      name: kitt
