version: '3.7'
services:
  vault:
    build: .
    hostname: "vault"
    restart: on-failure
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_LOG_LEVEL=debug
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SECURITY_TOKEN
      - AWS_SESSION_TOKEN
    volumes:
      - ./backup:/vault
    cap_add:
      - IPC_LOCK
  vault-proxy:
    image: letfn/consul-envoy:v1.8.0-v0.14.1
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
      SERVICE_CONFIG: /config/vault.hcl
      CENTRAL_CONFIG: /central_config/vault.hcl
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "vault"]
    network_mode: "service:vault"
  consul:
    environment:
      - "CONSUL_LOCAL_CONFIG={\"skip_leave_on_interrupt\": true, \"disable_update_check\": true}"
    image: docker.io/library/consul:1.8.0
    command: agent -client=0.0.0.0 -server -bootstrap-expect 1 -ui
    volumes:
      - "./etc/data/consul:/consul/data"
