#!/usr/bin/env bash

if ! $(which vault > /dev/null 2>&1); then
    echo "aborting unseal. please install the vault cli (vaultproject.io/downloads)"
    echo "first time running moria? please run make init before make unseal"
    exit 1
fi

if ! $(which pass > /dev/null 2>&1); then
    echo "aborting. please install pass (passwordstore.org) and pass-update (github.com/roddhjav/pass-update)"
    echo "first time running moria? please run make init before make unseal"
    exit 1
fi

index=1
while true
    do

        if $(pass moria/keys_$index > /dev/null 2>&1); then
            vault operator unseal > /dev/null 2>&1 $(pass moria/keys_$index)
	    index=$((index + 1))
        else
            break
        fi

    done

echo "vault status:"
vault status
