#!/usr/bin/env bash


if ! $(which pass > /dev/null 2>&1); then
    echo "aborting. please install pass (passwordstore.org) and pass-update (github.com/roddhjav/pass-update)"
    exit 1
fi

if test -f .initialized; then
    [ -r .init.csv ] && pass import bitwarden .init.csv
else
    [ -r .init.csv ] && pass import -f bitwarden .init.csv
fi

touch .initialized
